name: Daily Build of Blog

on:
  push:
    branches:
      - main  # Set a branch to deploy
  pull_request:
  schedule:
    - cron: '0 20 * * *' # Run at 4:00 AM UTC+8

jobs:
  deploy:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: 'latest'
          extended: true

      - name: Build
        run: hugo --minify

      # 新增的 Step: 自動添加 CNAME 檔案並提交
      - name: Add and Commit CNAME
        run: |
          echo "blog.collie.tw" > CNAME
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add CNAME
          git commit -m "Add CNAME for custom domain"

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
